Frontend + Pairing Service Integration
CS3219-AY2324S1/ay2324s1-course-assessment-g28 pull request #29
Opened 2023-09-26 19:32 UTC by zaiahkoh

Created a simple endpoint and form to handle communication between the frontend and the pairing microservice.
Very rough implementation with hardcoded values still being used.

Closes #11

2023-09-27 03:33 UTC, benmurphyy requested changes
I've integrated pairing with the existing Matching UI created by @teoyuqi 
What needs to be done:
1. remove the PairingCard component (this is covered by @teoyuqi matching card
2. remove the pairing page (same reason^)
3. Add readme to the pairing service (how to run the services)
4. Check that the pairing service works with the fe

2023-10-01 15:16 UTC, teoyuqi commented
works great on my end 👍🏻

2023-10-01 15:18 UTC, teoyuqi approved these changes

2023-10-01 15:26 UTC, teoyuqi commented on frontend/components/MatchingUI/MatchContext.tsx
> +          console.log(parsed);
just to check, is there a use case for `! parsed.data.url` && `status = 200`  && not match error? is it just considered match error already?

2023-10-01 15:27 UTC, teoyuqi commented on frontend/components/MatchingUI/MatchContext.tsx
> +          ws.close();
can consider moving `ws.close()` into a `finally` block since we will be closing it in error cases too

2023-10-05 04:40 UTC, benmurphyy requested changes

2023-10-05 04:40 UTC, benmurphyy commented on frontend/api/pairing/index.ts
> +const PAIRING_SERVICE = "ws://localhost:4000/pairing";
Remove the hardcoded values, add the port and url to the .env instead. Include information on the port number to use somewhere so we can use it

2023-10-05 04:40 UTC, benmurphyy commented on frontend/api/pairing/index.ts
> +const PAIRING_SERVICE = "ws://localhost:4000/pairing";
Other comments:
1. set up docker compose file in the pairing services
2. add config of the port to use for pairing in the docker compose file, probably taking the values from environment variables.
3. add simple explanation of pairing-front and pairing-back to README to understand their function.
4. Add instructions in the pairing services on how to run them (like port details and all that) Right now its quite unclear how they are connected to, and how they are supposed to be run

2023-10-05 10:50 UTC, benmurphyy approved these changes
Removed the hardcoding of pairing frontend url.
Added the url to the docker-compose environment variables for frontend.

2023-10-05 10:50 UTC, merged